version: "3"
services:
  mongodb:
    image: mongo:4.4.2-bionic
    container_name: mongoDB
    volumes:
      - ./database/mongo:/data/db
    restart: always
    ports:
      - "30017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
  api:
    depends_on: 
      - mongodb
    image: hayd/ubuntu-deno
    container_name: deno-server-api
    volumes:
      - "./:/opt"
    ports:
      - "5050:5050"
    working_dir: /opt
    command: deno run --allow-env --allow-read --allow-net server.ts