version: "3"
services:
  api:
    image: hayd/ubuntu-deno
    container_name: deno-server-api
    volumes:
      - "./:/opt"
    ports:
      - "5050:5050"
    working_dir: /opt
    command: deno run --allow-env --allow-read --allow-net /opt/server.ts